nvim-env --add alpha2phi https:///github.com/alpha2phi/neovim-for-minimalist
nvim-env --add NvChad https:///github.com/NvChad/Nvchad
nvim-env --add mnabila https:///github.com/mnabila/nvimrc
nvim-env --add AdiCahyaSaputra https:///github.com/AdiCahyaSaputra/my-neovim-setup
nvim-env --add doom-neovim https:///github.com/doom-neovim/doom-nvim
nvim-env --add fitrh https:///github.com/fitrh/init.nvim
nvim-env --add ariefra https:///github.com/ariefra/ar.nvim
nvim-env --add LazyVim https:///github.com/LazyVim/starter
nvim-env --add NvChad https:///github.com/NvChad/tinyvim
nvim-env --add AstroNvim https:///github.com/AstroNvim/AstroNvim
nvim-env --add Zeddnyx https:///github.com/Zeddnyx/Znvim
nvim-env --add LunarVim https:///github.com/LunarVim/LunarVim
nvim-env --add appelgriebsch https:///github.com/appelgriebsch/Nv
nvim-env --add domsch1988 https:///gitlab.com/domsch1988/mvim.git
